# Build stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o repocate ./cmd/repocate

# Final stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/repocate .
ENTRYPOINT ["./repocate"]