.TH REPOCATE 1 "August 2024" "Version 3.0.0" "User Commands"
.SH NAME
repocate \- A tool for managing development environments using Docker containers

.SH SYNOPSIS
.B repocate
.RI [ command ]
.RI [ options ]

.SH DESCRIPTION
.B Repocate
is a command-line tool designed to simplify the process of managing isolated development environments using Docker containers. It allows you to clone repositories, create development containers, enter containers, and manage them efficiently.

.SH COMMANDS
.TP
.BI "repocate create " "[repository URL or name]"
Clone a repository and create/start a development container for it.

.TP
.BI "repocate clone " "[repository URL]"
Clone a repository into the workspace directory.

.TP
.BI "repocate enter " "[repository URL or name]"
Enter the development container for the specified repository.

.TP
.BI "repocate stop " "[repository URL or name]"
Stop the development container for the specified repository.

.TP
.BI "repocate rebuild " "[repository URL or name]"
Rebuild the development container for the specified repository.

.TP
.BI "repocate list"
List all containers managed by repocate.

.TP
.BI "repocate version"
Show version information for repocate.

.TP
.BI "repocate help"
Show help information about repocate commands.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information about the command.

.SH EXAMPLES
.TP
.B repocate create https://github.com/cdaprod/repocate
Clone the repository and create/start a development container for it.

.TP
.B repocate enter repocate
Enter the development container for the "repocate" repository.

.TP
.B repocate list
List all containers managed by repocate.

.SH AUTHOR
Repocate was developed by David Cannan (Cdaprod) as a solution for streamlined development environment management using Docker containers.

.SH BUGS
For bug reports, please visit the GitHub issues page: https://github.com/cdaprod/repocate/issues

.SH COPYRIGHT
Repocate is released under the MIT License.