name: Build and Push Docker Images v3.0.0-<arch>

on:
  push:
    branches:
      - golang
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    strategy:
      matrix:
        arch: [amd64, arm64]  # Define architectures here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.repocate.package
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            cdaprod/repocate:v3.0.0-${{ matrix.arch }}

      - name: Post Log in to Docker Hub
        if: always()
        uses: docker/logout-action@v2