name: Deploy Repocate

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Load Docker cache
      run: |
        docker load --input /tmp/.buildx-cache

    - name: Deploy Docker image
      run: |
        docker run --rm -d \
          --name repocate-instance \
          -v ${{ secrets.HOST_VOLUME_PATH }}:/workspace \
          cdaprod/repocate:${{ github.sha }}

    - name: Clean up
      run: |
        docker system prune -f